### PR TITLE
Tests, Travis CI, Scrutinizer and Codecov

### PR DESCRIPTION
**Pull request by MarioBlazek**
Before merge please do following:
* enable Codecov
* enable TravisCI
* enable Scrutinizer
* create proper Github release with existing tag

### CODE REVIEW

**Comment by emodric** [comment]
Integrations activated.

@MarioBlazek Please run PHP CS Fixer.

Why do you need a release for a tag?

**Comment by MarioBlazek** [comment]
Release badge is displaying latest Github release.

**Comment by emodric** [comment]
@MarioBlazek Did you run PHP CS Fixer?

**Comment by MarioBlazek** [comment]
On this project we are using old php-cs-fixer configuration. Should I update config to new version like on other repos, etc this [one](https://github.com/netgen/NetgenEnhancedSelectionBundle/blob/master/.php_cs) ?

**Comment by emodric** [comment]
@MarioBlazek I've pushed PHP CS Fixer 2.0 rules, you can rebase and run the fixer.

**Comment by MarioBlazek** [comment]
@emodric done.

**Comment by emodric** [comment]
Thanks! :+1:

**Pull request merged**
